### ISSUE TITLE
What's the open source plan?

### ISSUE THREAD

**Issue by plalx** [WaltonChain/WaltonChain_Gwtc_Src#1]
I was hoping the entire commit history would be released and that this repository would become the sole home for Gwtc's node source code meaning that Waltonchain employees would use this repository as their centralized origin. The way it's setup right now hints that future development will be ongoing internally and that a source dump will be pushed to GitHub when milestones are reached. I hope that's not the plan, is it?

**Comment by DennyWeinberg** [comment]
It's also interesting (bad) they didn't use the github fork feature. All history before today is lost and can't be shown within this project.

**Comment by disy-yin** [comment]
WTC inherits from ethereum v1.7.1stable.
At the same time, this repository will remain the only development repository in the future while keeping all development submission records.

Thank you for your attention.

**Comment by plalx** [comment]
Yeah I had figured it was `1.7.1` during limited community testing ;) 

> "this repository will remain the only development repository in the future"

This is great news and what I was hoping for. You may want to rename the repositories to make things a little more organized. We dont need "Waltonchain" to be repeated in all repository names. I'd only call this repository "gwtc" or "go-wtc" and if you wish to have static build releases you can use the GitHub's release feature where you can attach assets to the release (e.g. zipped binaries). The same goas for all other repositories (e.g. "Waltonchain_CrossChain" -> "CrossChain" or even better normalize to all lowercased repos "cross-chain" to be standard).

**Comment by disy-yin** [comment]
好的。多谢。
你的建议非常好。
我们后续将整理这些。

**Comment by disy-yin** [comment]
All right.Thank you very much.
Your suggestion is very good.
We'll sort this out later.
