### ISSUE TITLE
Unintentional replacements

### ISSUE THREAD

**Issue by DennyWeinberg** [WaltonChain/WaltonChain_Gwtc_Src#2]
`together` was unintentionally replaced by `togwtcer`.
Please replace back these comments. Others might have the same "issue".

**Comment by simplest-circuits** [comment]
This isn't an issue, because the variable means togETHer and togWTCer, I think that's correct.

**Comment by DennyWeinberg** [comment]
@disy-yin, could you please tell me the revision you used as base? So when you did the "fork"/copy of the original code?

**Comment by WaltonChain** [comment]
> `together` was unintentionally replaced by `togwtcer`.
> Please replace back these comments. Others might have the same "issue".
> 
> Otherwise there are many differences compared to the original go eth code. Nice job!

Has been resolved

**Comment by disy-yin** [comment]
> `together` was unintentionally replaced by `togwtcer`.
> Please replace back these comments. Others might have the same "issue".

Has been resolved

**Comment by DennyWeinberg** [comment]
@disy-yin what about the revision?

**Comment by disy-yin** [comment]
> @disy-yin what about the revision?

1.7.1stable
